.github/workflows/trivy-analysis.yml

Add initial Trivy workflow

---

.github/workflows/ledger-test.yml
test/docker-compose.yaml
test/init-test-network.sh

Added workflow to start the ledger and use the ledger browser to check the ledgers state.

add test ledger workflow

---

.github/workflows/build-buster.yml
.github/workflows/build-ubuntu18.yml

disable latest tag for ubuntu build

---

build/Dockerfile.buster
build/Dockerfile.ubuntu18
build/init_and_run.sh
minutes/2021-08-20.md

fixes https://github.com/IDunion/indy-node-container/issues/33

running as indy user

---

controller/Dockerfile
controller/README.md
controller/container_node_control_tool.py
controller/init_and_run.sh
controller/restart_indy_node.sh
controller/start_node_control_tool

Indy node controller container image for docker and podman.
The image is not as clean as I would like due to conflicting requirements of libindy and podman. That being said it shouldn't lead to any problems since the controller only requires access to basic constants and helper functions from libindy

Add controller container

---

controller/Dockerfile
controller/container_node_control_tool.py
controller/restart_indy_node.sh
controller/upgrade_indy.sh
test/docker-compose.yaml
test/init-test-network.sh

Implementation of a simple node image upgrade mechanism that rebuilds and restrarts the node container if a new image can be pulled independent of the used orchestration tool such as docker-compose.

Add node upgrade logic for the controller

---

.github/workflows/build-all.yml
.github/workflows/trivy-all.yml
Makefile
build/Dockerfile.ubuntu20
run/docker-compose.yml

This PR contains the Ubuntu 20.04 Indy-Node image. The artifacts used are released in the development state.
Signed-off-by: udosson <r.klemens@yahoo.de>

added ubuntu 20.04 test image for indy node

---

build/Dockerfile.ubuntu18

to have `ss` avaiable for debugging

add iproute2 package to the container 

---

.github/workflows/build-all.yml

Signed-off-by: udosson <klemens@internet-sicherheit.de>

ignore *.md files and NOTICE file as trigger for GHA workflow

---

test/README.md

readme.md
Signed-off-by: Kevin Wollowski <wollowski@internet-sicherheit.de>

added prerequisites and a step by step guide for test/run

---

.gitignore
build/Dockerfile.bullseye
build/Dockerfile.buster

fixes https://github.com/hyperledger/indy-node-container/issues/69

debian containers adapted to use old ubuntu 16 (crypto) libs

---

.github/workflows/build-all.yml
README.md

batch with relativ url not working. fixed.

---

.github/workflows/trivy-all.yml

fix trivy job

---

Makefile
NOTICE
README.md
trivy/html.tpl

fixes #86
Signed-off-by: Guido Wischrop <Guido.Wischrop@mgm-tp.com>

Update README, small fix for trivy html template

---

build/Dockerfile.ubuntu20

This includes all changes from the indy node ubuntu20 branch.

update to latest indy node from ubuntu20 branch

---

build/Dockerfile.ubuntu20

Based on 
- https://github.com/hyperledger/indy-node/releases/v1.13.1-rc2 
- https://github.com/hyperledger/indy-plenum/releases/v1.13.1-rc2

Ubuntu20 image based on ubuntu20 RC2

---

run/.env
run/README.md
run/docker-compose.yml

I have compared the [test docker compose](https://github.com/hyperledger/indy-node-container/blob/main/test/docker-compose.yaml) which is regularly tested to produce a working setup for the restart process, with the [production one](https://github.com/hyperledger/indy-node-container/blob/main/run/docker-compose.yml) to produce the changes

fixed env variable name. Fixes #95

---

build/Dockerfile.ubuntu16

fixes https://github.com/hyperledger/indy-node-container/issues/100

added explicit plenum version to ubuntu16 Docker file

---

controller/README.md
controller/upgrade_indy.sh

Fixes an old copypaste error which overwrote an image name variable causing an error in the upgrade script (See line 64). Additionally some overall readability improvements have been applied and out of date documentation corrected.

Fix controller regression errors

---

build/Dockerfile.ubuntu20

New release candidate for the ubuntu20 image
Signed-off-by: Christian Bormann <ChristianCarl.Bormann@de.bosch.com>

Use new rc3 for ubuntu 20

---

run/README.md
run/etc_indy/indy_config.py

Update README.md + cfg for ubuntu 1.13 test container

---

run/README.md
run/add_ddos_protection_iptables_rule.sh
run/ip_tables_utils.sh
run/set_iptables.sh

- Calling the CLI port settings script from the first one
- extracting common functionality into utility script

Ip tables scripts improved

---

run/README.md

Extended run howto in readme

---

controller/Dockerfile

fixes https://github.com/hyperledger/indy-node-container/issues/112

112 podman

---

build/Dockerfile.ubuntu20

Uses
- indy-node-v1.13.2-rc4
- indy-plenum-v1.13.1-rc3

New image for node-1.13.2-rc4

---

run/README.md
run/add_ddos_protection_iptables_rule.sh
run/check_network_connectivity.sh
run/ip_tables_utils.sh
run/set_iptables.sh

added script to test network connectivity between the network nodes (firewall, routing, etc.)

Network connectivity test script

---

run/etc_indy/node_control.confe

fixes https://github.com/hyperledger/indy-node-container/issues/103

removed trash

---

MAINTAINERS.md

adding philipp as maintainer

---

run/add_ddos_protection_iptables_rule.sh

important ddos script fix: do not always enter test mode

---

run/README.md

Changed YOUR_NETWQRK_NAME to YOUR_NETWORK_NAME.

fix typo in README.md

---

.github/workflows/build-all.yml
README.md
build/Dockerfile.debian11
build/Dockerfile.debian12
build/Dockerfile.ubuntu20
build/Dockerfile.ubuntu22

ubuntu 22 image
